### ISSUE TITLE
Paste and mask definition not ideal for many footprints

### ISSUE THREAD

**Issue by poeschlr** [KiCad/Housings_BGA.pretty#16]
@savenlid brought to our attention that for many bga footprints there is a recommendation for square paste openings.
Example from http://www.cypress.com/file/45826/download
> Typical BGA stencils are designed with round apertures; however, Cypress recommends square apertures for better paste release.

This would mean removing the paste layer from the round pads and placing paste only pads with the correct size on top of it.

Another problem with many footprints is that the mask clearance is not defined at all. Most bga footprints need a lower clearance setting than will be used on a typical pcb. It might be a good idea to set it on a footprint or even pad basis.

**Comment by poeschlr** [comment]
More details see discussion in https://github.com/KiCad/Resistors_SMD.pretty/pull/10

**Comment by evanshultz** [comment]
I just came across something similar on another BGA part. See page 6 of http://www.ti.com/lit/an/snva009ag/snva009ag.pdf. Not exactly related, but similar in that it's a BGA with a defined stencil opening recommendation.

I discussed and implemented differently-sized pads and stencil openings on the Cree LED footprints at https://github.com/KiCad/LEDs.pretty/pull/39, including proposing an embellishment to KLC that covers how to construct pads in this case.

**Comment by evanshultz** [comment]
Some work done on this in https://github.com/KiCad/Housings_BGA.pretty/pull/17, and questions asked. I'll happily do the other Texas footprints after that PR is merged, if all agree.

One note: the TI app note wants square pads with rounded corners, but we can't do that in the released library yet for known reasons. I'm not sure if there's a good way to make a to-do list for a repo? Although ugly, we could possibly use the README.md file.

**Comment by poeschlr** [comment]
@evanshultz wrote:
> I'm not sure if there's a good way to make a to-do list for a repo?

Isn't this what issues are there for?

**Comment by SchrodingersGat** [comment]
@poeschlr please readdress this to the new repo :)
