### ISSUE TITLE
write-access for maintainers

### ISSUE THREAD

**Issue by jkriege2** [KiCad/Housings_BGA.pretty#2]
Hi @SchrodingersGat could you give the maintainers write-access to this? Then I can review ... + what about also haveong PGA, LGA repos?

JAN

**Comment by SchrodingersGat** [comment]
https://github.com/KiCad/Housings_PGA.pretty

https://github.com/KiCad/Housings_LGA.pretty

**Comment by jkriege2** [comment]
Great!

Thanks,
JAN
